// <auto-generated />
namespace EURO2020.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedplayerphoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedplayerphoto));
        
        string IMigrationMetadata.Id
        {
            get { return "202106221446046_Added player photo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
